import { defineAsyncComponent, h, Suspense, type Component } from 'vue'
import LoadingSpinner from '@/ui/components/LoadingSpinner.vue'
import ErrorComponent from '@/ui/components/ErrorComponent.vue'

const componentCache = new Map<Function, Component>()
const prefetchedRoutes = new Set<string>()

export function loadView(
  loader: () => Promise<Component>,
  loadingComponent: Component = LoadingSpinner,
  errorComponent: Component = ErrorComponent
) {
  let component = componentCache.get(loader)
  if (!component) {
    component = defineAsyncComponent({
      loader,
      errorComponent,
      delay: 0
    })
    componentCache.set(loader, component)
  }
  return {
    render() {
      return h(
        Suspense,
        {},
        {
          default: () => h(component),
          fallback: () => h(loadingComponent)
        }
      )
    }
    // !!!! example of using AsyncView !!!!
    // render() {
    //   return h(AsyncView, {
    //     component,
    //     loadingComponent,
    //     errorComponent
    //   })
    // }
  }
}

export function preloadView(viewName: string) {
  import(`@/ui/views/${viewName}.vue`)
}

/**
 * Prefetch all chunks for a route (JS, CSS, and IoC dependencies)
 * Uses the route-deps-map generated by vite-chunks-map-plugin
 */
export async function prefetchRoute(routePath: string): Promise<void> {
  // Prevent duplicate prefetching
  if (prefetchedRoutes.has(routePath)) return
  prefetchedRoutes.add(routePath)

  try {
    // Import the route deps map (generated at build time)
    const { default: routeDepsMap } = await import('virtual:route-deps-map')
    const chunks = routeDepsMap[routePath]
    
    if (!chunks || chunks.length === 0) return

    // Prefetch each chunk (only JS - CSS is auto-injected by Vite when JS loads)
    for (const chunk of chunks) {
      // Skip CSS - Vite automatically injects CSS when the JS module loads
      if (chunk.endsWith('.css')) continue
      
      if (chunk.endsWith('.js')) {
        const href = import.meta.env.BASE_URL + chunk
        
        // Check if already preloaded
        if (document.querySelector(`link[href="${href}"]`)) continue
        
        const link = document.createElement('link')
        link.rel = 'modulepreload'
        link.href = href
        document.head.appendChild(link)
      }
    }
  } catch (e) {
    // Fallback: in dev mode, route-deps-map doesn't exist
    // Just silently fail or use preloadView as fallback
    console.debug('[prefetchRoute] Route deps map not available (expected in dev mode)')
  }
}
